// <auto-generated />
using System;
using MetaHub.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetaHub.Infrastructure.Migrations
{
    [DbContext(typeof(MetaHubDbContext))]
    partial class MetaHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetaHub.Domain.Entities.BookDetail", b =>
                {
                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Isbn13")
                        .HasColumnType("text");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<double?>("SeriesIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("SeriesName")
                        .HasColumnType("text");

                    b.HasKey("WorkId");

                    b.HasIndex("Isbn13");

                    b.ToTable("book_details", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Character")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("WorkId", "PersonId", "Role");

                    b.ToTable("credits", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AbsoluteNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesWorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeriesWorkId", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.ExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.HasIndex("Source", "ExternalValue")
                        .IsUnique();

                    b.ToTable("external_ids", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Lang")
                        .HasColumnType("text");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "Type");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcoustId")
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Crc32")
                        .HasColumnType("text");

                    b.Property<string>("Ed2kHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("IdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MbRecording")
                        .HasColumnType("text");

                    b.Property<string>("MovieHash")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcoustId");

                    b.HasIndex("Ed2kHash");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("WorkId");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.MusicDetail", b =>
                {
                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("AlbumType")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<int?>("TrackCount")
                        .HasColumnType("integer");

                    b.HasKey("WorkId");

                    b.ToTable("music_details", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bios")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.RawPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "Source");

                    b.ToTable("raw_payloads", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.SeriesDetail", b =>
                {
                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Network")
                        .HasColumnType("text");

                    b.Property<int?>("SeasonCount")
                        .HasColumnType("integer");

                    b.HasKey("WorkId");

                    b.ToTable("series_details", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.SourceFetchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CallsInWindow")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastCallAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .IsUnique();

                    b.ToTable("source_fetch_logs", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumWorkId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("LengthMs")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumWorkId", "DiscNumber", "TrackNumber");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("OverviewTranslations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTitle");

                    b.HasIndex("MediaType");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.WorkGenre", b =>
                {
                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("work_genres", (string)null);
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.BookDetail", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithOne("BookDetail")
                        .HasForeignKey("MetaHub.Domain.Entities.BookDetail", "WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Credit", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Person", "Person")
                        .WithMany("Credits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithMany("Credits")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Episode", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.SeriesDetail", "Series")
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.ExternalId", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithMany("ExternalIds")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Image", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithMany("Images")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Episode", "Episode")
                        .WithMany("MediaFiles")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithMany("MediaFiles")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Episode");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.MusicDetail", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithOne("MusicDetail")
                        .HasForeignKey("MetaHub.Domain.Entities.MusicDetail", "WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.RawPayload", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithMany("RawPayloads")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.SeriesDetail", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithOne("SeriesDetail")
                        .HasForeignKey("MetaHub.Domain.Entities.SeriesDetail", "WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Track", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.MusicDetail", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.WorkGenre", b =>
                {
                    b.HasOne("MetaHub.Domain.Entities.Genre", "Genre")
                        .WithMany("WorkGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetaHub.Domain.Entities.Work", "Work")
                        .WithMany("WorkGenres")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Episode", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Genre", b =>
                {
                    b.Navigation("WorkGenres");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.MusicDetail", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Person", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.SeriesDetail", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("MetaHub.Domain.Entities.Work", b =>
                {
                    b.Navigation("BookDetail");

                    b.Navigation("Credits");

                    b.Navigation("ExternalIds");

                    b.Navigation("Images");

                    b.Navigation("MediaFiles");

                    b.Navigation("MusicDetail");

                    b.Navigation("RawPayloads");

                    b.Navigation("SeriesDetail");

                    b.Navigation("WorkGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
